# -*- coding: utf-8 -*-
"""
Created on Tue Sep  8 11:14:17 2020

@author: javi8
"""

MainBoard_16x16 = {'aiChannels': {'Ch01': ('ai0', 'ai8'),
                                  'Ch02': ('ai1', 'ai9'),
                                  'Ch03': ('ai2', 'ai10'),
                                  'Ch04': ('ai3', 'ai11'),
                                  'Ch05': ('ai4', 'ai12'),
                                  'Ch06': ('ai5', 'ai13'),
                                  'Ch07': ('ai6', 'ai14'),
                                  'Ch08': ('ai7', 'ai15'),
                                  'Ch09': ('ai16', 'ai24'),
                                  'Ch10': ('ai17', 'ai25'),
                                  'Ch11': ('ai18', 'ai26'),
                                  'Ch12': ('ai19', 'ai27'),
                                  'Ch13': ('ai20', 'ai28'),
                                  'Ch14': ('ai21', 'ai29'),
                                  'Ch15': ('ai22', 'ai30'),
                                  'Ch16': ('ai23', 'ai31')},

                   'aoChannels': {'ChVs': 'ao1',
                                  'ChVds': 'ao0',
                                  'ChAo2': None,
                                  'ChAo3': None, },

                   'ColOuts': {'Col05': ('line0', 'line1'),
                               'Col06': ('line2', 'line3'),
                               'Col08': ('line4', 'line5'),
                               'Col07': ('line6', 'line7'),
                               'Col02': ('line8', 'line9'),
                               'Col04': ('line10', 'line11'),
                               'Col01': ('line12', 'line13'),
                               'Col03': ('line14', 'line15'),
                               'Col16': ('line16', 'line17'),
                               'Col15': ('line18', 'line19'),
                               'Col13': ('line20', 'line21'),
                               'Col14': ('line22', 'line23'),
                               'Col11': ('line24', 'line25'),
                               'Col09': ('line26', 'line27'),
                               'Col12': ('line28', 'line29'),
                               'Col10': ('line30', 'line31'),
                               }, }

MainBoard_8x8 = {'aiChannels': {'Ch01': ('ai0', 'ai8'),
                                'Ch02': ('ai1', 'ai9'),
                                'Ch03': ('ai2', 'ai10'),
                                'Ch04': ('ai3', 'ai11'),
                                'Ch05': ('ai4', 'ai12'),
                                'Ch06': ('ai5', 'ai13'),
                                'Ch07': ('ai6', 'ai14'),
                                'Ch08': ('ai7', 'ai15'),
                                'Ch09': ('ai16', 'ai24'),
                                'Ch10': ('ai17', 'ai25'),
                                'Ch11': ('ai18', 'ai26'),
                                'Ch12': ('ai19', 'ai27'),
                                'Ch13': ('ai20', 'ai28'),
                                'Ch14': ('ai21', 'ai29'),
                                'Ch15': ('ai22', 'ai30'),
                                'Ch16': ('ai23', 'ai31')},

                 'aoChannels': {'ChVs': 'ao1',
                                'ChVds': 'ao0',
                                'ChAo2': None,
                                'ChAo3': None, },

                 'ColOuts': {'Col1': ('line0', 'line1'),
                             'Col2': ('line2', 'line3'),
                             'Col3': ('line4', 'line5'),
                             'Col4': ('line6', 'line7'),
                             'Col5': ('line8', 'line9'),
                             'Col6': ('line10', 'line11'),
                             'Col7': ('line12', 'line13'),
                             'Col8': ('line14', 'line15'),
                             }, }

Mos2 = {'aiChannels': {'Ch01': ('ai0', 'ai8'),
                       'Ch02': ('ai1', 'ai9'),
                       'Ch03': ('ai2', 'ai10'),
                       'Ch04': ('ai3', 'ai11'),
                       'Ch05': ('ai4', 'ai12'),
                       'Ch06': ('ai5', 'ai13'),
                       'Ch07': ('ai6', 'ai14'),
                       'Ch08': ('ai7', 'ai15'),
                       'Ch09': ('ai16', 'ai24'),
                       'Ch10': ('ai17', 'ai25'),
                       'Ch11': ('ai18', 'ai26'),
                       'Ch12': ('ai19', 'ai27'),
                       'Ch13': ('ai20', 'ai28'),
                       'Ch14': ('ai21', 'ai29'),
                       'Ch15': ('ai22', 'ai30'),
                       'Ch16': ('ai23', 'ai31')},

        'aoChannels': {'ChVs': 'ao1',
                       'ChVds': 'ao0',
                       'ChAo2': 'ao2',
                       'ChAo3': 'ao3', },

        'ColOuts': {'Col04': ('line0', ),
                    'Col01': ('line1', ),
                    'Col02': ('line2', ),
                    'Col03': ('line3', ),
                    'Col08': ('line4', ),
                    'Col05': ('line5', ),
                    'Col07': ('line6', ),
                    'Col06': ('line7', ),                    
                    'Col09': ('line8', ),
                    'Col12': ('line9', ),
                    'Col11': ('line10', ),
                    'Col10': ('line11', ),
                    'Col13': ('line12', ),
                    'Col16': ('line13', ),
                    'Col15': ('line14', ),
                    'Col14': ('line15', ),
                    }, }

MB41 = {'aiChannels': {'Ch09': ('ai0', 'ai8'),
                       'Ch10': ('ai1', 'ai9'),
                       'Ch11': ('ai2', 'ai10'),
                       'Ch12': ('ai3', 'ai11'),
                       'Ch13': ('ai4', 'ai12'),
                       'Ch14': ('ai5', 'ai13'),
                       'Ch15': ('ai6', 'ai14'),
                       'Ch16': ('ai7', 'ai15'),
                       'Ch01': ('ai16', 'ai24'),
                       'Ch02': ('ai17', 'ai25'),
                       'Ch03': ('ai18', 'ai26'),
                       'Ch04': ('ai19', 'ai27'),
                       'Ch05': ('ai20', 'ai28'),
                       'Ch06': ('ai21', 'ai29'),
                       'Ch07': ('ai22', 'ai30'),
                       'Ch08': ('ai23', 'ai31'),
                       },

        'aoChannels': {'ChVs': 'ao1',
                       'ChVds': 'ao0',
                       'ChAo2': None,
                       'ChAo3': None, },

        'ColOuts': {'Col10': ('line0', 'line1'),
                    'Col09': ('line2', 'line3'),
                    'Col12': ('line4', 'line5'),
                    'Col11': ('line6', 'line7'),
                    'Col15': ('line8', 'line9'),
                    'Col16': ('line10', 'line11'),
                    'Col13': ('line12', 'line13'),
                    'Col14': ('line14', 'line15'),
                    'Col02': ('line16', 'line17'),
                    'Col01': ('line18', 'line19'),
                    'Col04': ('line20', 'line21'),
                    'Col03': ('line22', 'line23'),
                    'Col07': ('line24', 'line25'),
                    'Col08': ('line26', 'line27'),
                    'Col05': ('line28', 'line29'),
                    'Col06': ('line30', 'line31'),
                    }, }

MB42 = {'aiChannels': {'Ch09': ('ai0', 'ai8'),
                       'Ch10': ('ai1', 'ai9'),
                       'Ch11': ('ai2', 'ai10'),
                       'Ch12': ('ai3', 'ai11'),
                       'Ch13': ('ai4', 'ai12'),
                       'Ch14': ('ai5', 'ai13'),
                       'Ch15': ('ai6', 'ai14'),
                       'Ch16': ('ai7', 'ai15'),
                       'Ch01': ('ai16', 'ai24'),
                       'Ch02': ('ai17', 'ai25'),
                       'Ch03': ('ai18', 'ai26'),
                       'Ch04': ('ai19', 'ai27'),
                       'Ch05': ('ai20', 'ai28'),
                       'Ch06': ('ai21', 'ai29'),
                       'Ch07': ('ai22', 'ai30'),
                       'Ch08': ('ai23', 'ai31'),
                       },

        'aoChannels': {'ChVs': 'ao1',
                       'ChVds': 'ao0',
                       'ChAo2': None,
                       'ChAo3': None, },

        'ColOuts':  {'Col10': ('line0', ),
                     'Col09': ('line1', ),
                     'Col12': ('line2', ),
                     'Col11': ('line3', ),
                     'Col15': ('line4', ),
                     'Col16': ('line5', ),
                     'Col13': ('line6', ),
                     'Col14': ('line7', ),
                     'Col02': ('line8', ),
                     'Col01': ('line9', ),
                     'Col04': ('line10', ),
                     'Col03': ('line11', ),
                     'Col07': ('line12', ),
                     'Col08': ('line13', ),
                     'Col05': ('line14', ),
                     'Col06': ('line15', ),        
                     }, }


HwConfig = {'MainBoard_16x16': MainBoard_16x16,
            'MainBoard_8x8': MainBoard_8x8,
            'Mos2': Mos2,
            'MB41': MB41,
            'MB42': MB42}
